name: Getting started

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:



jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ linux-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: sh ./.github/workflows/github-actions-script.sh

      - name: Run a multi-line script
        run: |
          echo Nothing to see in the milti-line script
          echo Here is what is in the folder:
          ls -a
          
